spring:
  application:
    name: microservice-profile
    microservice-customer:
      url: http://localhost:8000

  devtools:
    restart:
      enabled: true

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: profile

server:
  port: 8000
  servlet:
    context-path: /profile